[env:t-display-amoled]
platform = espressif32 @ 6.5.0
board = esp32-s3-devkitc-1
framework = arduino

# --- SPECYFIKACJA SPRZĘTOWA LILYGO 1.91' ---
# Ten model wymaga trybu QIO dla Flash i OPI dla PSRAM
board_build.arduino.memory_type = qio_opi 
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

# --- KOMUNIKACJA ---
monitor_speed = 115200
upload_speed = 921600
# To wymusza, by Serial działał przez wbudowane USB-C
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM
    -std=gnu++2a
    -DLV_CONF_INCLUDE_SIMPLE
    -I src
    -w # wyciszenie ostrzeżeń

# --- NARZĘDZIA ---
platform_packages =
    toolchain-xtensa-esp32s3 @ 12.2.0+20230208

monitor_filters = esp32_exception_decoder, time

lib_deps = 
    lvgl/lvgl @ 8.3.11
    https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series.git