// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: display

#ifndef _DISPLAY_UI_H
#define _DISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_n_bacground_gt7_png);    // assets/n_bacground_gt7.png
LV_IMG_DECLARE(ui_img_fuel_slider_rgb2_png);    // assets/fuel_slider_RGB2.png
LV_IMG_DECLARE(ui_img_kolo_png);    // assets/kolo.png
LV_IMG_DECLARE(ui_img_arrow_png);    // assets/Arrow.png

// FONTS
LV_FONT_DECLARE(ui_font_big28);
LV_FONT_DECLARE(ui_font_big32);
LV_FONT_DECLARE(ui_font_big48);
LV_FONT_DECLARE(ui_font_big84);
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
