// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: display

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_BACKGROUND;
extern lv_obj_t * ui_TIreConteainer;
extern lv_obj_t * ui_LFtire;
extern lv_obj_t * ui_RFtire;
extern lv_obj_t * ui_RRtire;
extern lv_obj_t * ui_LRtire;
extern lv_obj_t * ui_FLTIRETEMPblack;
extern lv_obj_t * ui_FLTIRETEMPwhite;
extern lv_obj_t * ui_FRTIRETEMPblack;
extern lv_obj_t * ui_FRTIRETEMPwhite;
extern lv_obj_t * ui_RLTIRETEMPblack;
extern lv_obj_t * ui_RLTIRETEMPwhite;
extern lv_obj_t * ui_RRTIRETEMPblack;
extern lv_obj_t * ui_RRTIRETEMPwhite;
extern lv_obj_t * ui_LAPCOUNTERshadow;
extern lv_obj_t * ui_LAPCOUNTERbase;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_LAPCOUNTERshadow1;
extern lv_obj_t * ui_LAPCOUNTERbase1;
extern lv_obj_t * ui_AVGfuel;
extern lv_obj_t * ui_AzimuthAngle;
extern lv_obj_t * ui_AzimuthLebel;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Arrow;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

