// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: display

#include "ui.h"

lv_obj_t * ui_Screen1;
lv_obj_t * ui_BACKGROUND;
lv_obj_t * ui_TIreConteainer;
lv_obj_t * ui_LFtire;
lv_obj_t * ui_RFtire;
lv_obj_t * ui_RRtire;
lv_obj_t * ui_LRtire;
lv_obj_t * ui_FLTIRETEMPblack;
lv_obj_t * ui_FLTIRETEMPwhite;
lv_obj_t * ui_FRTIRETEMPblack;
lv_obj_t * ui_FRTIRETEMPwhite;
lv_obj_t * ui_RLTIRETEMPblack;
lv_obj_t * ui_RLTIRETEMPwhite;
lv_obj_t * ui_RRTIRETEMPblack;
lv_obj_t * ui_RRTIRETEMPwhite;
lv_obj_t * ui_LAPCOUNTERshadow;
lv_obj_t * ui_LAPCOUNTERbase;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_LAPCOUNTERshadow1;
lv_obj_t * ui_LAPCOUNTERbase1;
lv_obj_t * ui_AVGfuel;
lv_obj_t * ui_AzimuthAngle;
lv_obj_t * ui_AzimuthLebel;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Arrow;

// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BACKGROUND = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_BACKGROUND, &ui_img_n_bacground_gt7_png);
    lv_obj_set_width(ui_BACKGROUND, LV_SIZE_CONTENT);   /// 536
    lv_obj_set_height(ui_BACKGROUND, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_BACKGROUND, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACKGROUND, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BACKGROUND, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TIreConteainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_TIreConteainer);
    lv_obj_set_width(ui_TIreConteainer, 228);
    lv_obj_set_height(ui_TIreConteainer, 231);
    lv_obj_set_x(ui_TIreConteainer, 90);
    lv_obj_set_y(ui_TIreConteainer, -1);
    lv_obj_set_align(ui_TIreConteainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TIreConteainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LFtire = lv_obj_create(ui_TIreConteainer);
    lv_obj_set_width(ui_LFtire, 55);
    lv_obj_set_height(ui_LFtire, 107);
    lv_obj_set_x(ui_LFtire, 0);
    lv_obj_set_y(ui_LFtire, -60);
    lv_obj_set_align(ui_LFtire, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LFtire, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LFtire, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LFtire, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LFtire, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_LFtire, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RFtire = lv_obj_create(ui_TIreConteainer);
    lv_obj_set_width(ui_RFtire, 54);
    lv_obj_set_height(ui_RFtire, 107);
    lv_obj_set_x(ui_RFtire, 80);
    lv_obj_set_y(ui_RFtire, -60);
    lv_obj_set_align(ui_RFtire, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RFtire, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RFtire, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RFtire, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RFtire, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_RFtire, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RRtire = lv_obj_create(ui_TIreConteainer);
    lv_obj_set_width(ui_RRtire, 54);
    lv_obj_set_height(ui_RRtire, 107);
    lv_obj_set_x(ui_RRtire, 80);
    lv_obj_set_y(ui_RRtire, 59);
    lv_obj_set_align(ui_RRtire, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RRtire, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RRtire, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RRtire, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RRtire, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_RRtire, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LRtire = lv_obj_create(ui_TIreConteainer);
    lv_obj_set_width(ui_LRtire, 55);
    lv_obj_set_height(ui_LRtire, 107);
    lv_obj_set_x(ui_LRtire, 0);
    lv_obj_set_y(ui_LRtire, 59);
    lv_obj_set_align(ui_LRtire, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LRtire, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LRtire, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LRtire, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LRtire, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_LRtire, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FLTIRETEMPblack = lv_label_create(ui_TIreConteainer);
    lv_obj_set_width(ui_FLTIRETEMPblack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FLTIRETEMPblack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FLTIRETEMPblack, 0);
    lv_obj_set_y(ui_FLTIRETEMPblack, -53);
    lv_obj_set_align(ui_FLTIRETEMPblack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FLTIRETEMPblack, "000");
    lv_obj_add_flag(ui_FLTIRETEMPblack, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_FLTIRETEMPblack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FLTIRETEMPblack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FLTIRETEMPblack, &ui_font_big32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FLTIRETEMPwhite = lv_label_create(ui_TIreConteainer);
    lv_obj_set_width(ui_FLTIRETEMPwhite, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FLTIRETEMPwhite, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FLTIRETEMPwhite, -3);
    lv_obj_set_y(ui_FLTIRETEMPwhite, -58);
    lv_obj_set_align(ui_FLTIRETEMPwhite, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FLTIRETEMPwhite, "000");
    lv_obj_set_style_text_color(ui_FLTIRETEMPwhite, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FLTIRETEMPwhite, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FLTIRETEMPwhite, &ui_font_big32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FRTIRETEMPblack = lv_label_create(ui_TIreConteainer);
    lv_obj_set_width(ui_FRTIRETEMPblack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FRTIRETEMPblack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FRTIRETEMPblack, 80);
    lv_obj_set_y(ui_FRTIRETEMPblack, -55);
    lv_obj_set_align(ui_FRTIRETEMPblack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FRTIRETEMPblack, "000");
    lv_obj_add_flag(ui_FRTIRETEMPblack, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_FRTIRETEMPblack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FRTIRETEMPblack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FRTIRETEMPblack, &ui_font_big32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FRTIRETEMPwhite = lv_label_create(ui_TIreConteainer);
    lv_obj_set_width(ui_FRTIRETEMPwhite, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FRTIRETEMPwhite, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FRTIRETEMPwhite, 77);
    lv_obj_set_y(ui_FRTIRETEMPwhite, -58);
    lv_obj_set_align(ui_FRTIRETEMPwhite, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FRTIRETEMPwhite, "000");
    lv_obj_set_style_text_color(ui_FRTIRETEMPwhite, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FRTIRETEMPwhite, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FRTIRETEMPwhite, &ui_font_big32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RLTIRETEMPblack = lv_label_create(ui_TIreConteainer);
    lv_obj_set_width(ui_RLTIRETEMPblack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RLTIRETEMPblack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RLTIRETEMPblack, 0);
    lv_obj_set_y(ui_RLTIRETEMPblack, 65);
    lv_obj_set_align(ui_RLTIRETEMPblack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RLTIRETEMPblack, "000");
    lv_obj_add_flag(ui_RLTIRETEMPblack, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_RLTIRETEMPblack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RLTIRETEMPblack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RLTIRETEMPblack, &ui_font_big32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RLTIRETEMPwhite = lv_label_create(ui_TIreConteainer);
    lv_obj_set_width(ui_RLTIRETEMPwhite, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RLTIRETEMPwhite, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RLTIRETEMPwhite, -3);
    lv_obj_set_y(ui_RLTIRETEMPwhite, 62);
    lv_obj_set_align(ui_RLTIRETEMPwhite, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RLTIRETEMPwhite, "000");
    lv_obj_set_style_text_color(ui_RLTIRETEMPwhite, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RLTIRETEMPwhite, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RLTIRETEMPwhite, &ui_font_big32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RRTIRETEMPblack = lv_label_create(ui_TIreConteainer);
    lv_obj_set_width(ui_RRTIRETEMPblack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RRTIRETEMPblack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RRTIRETEMPblack, 80);
    lv_obj_set_y(ui_RRTIRETEMPblack, 65);
    lv_obj_set_align(ui_RRTIRETEMPblack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RRTIRETEMPblack, "000");
    lv_obj_add_flag(ui_RRTIRETEMPblack, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_RRTIRETEMPblack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RRTIRETEMPblack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RRTIRETEMPblack, &ui_font_big32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RRTIRETEMPwhite = lv_label_create(ui_TIreConteainer);
    lv_obj_set_width(ui_RRTIRETEMPwhite, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RRTIRETEMPwhite, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RRTIRETEMPwhite, 77);
    lv_obj_set_y(ui_RRTIRETEMPwhite, 62);
    lv_obj_set_align(ui_RRTIRETEMPwhite, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RRTIRETEMPwhite, "000");
    lv_obj_set_style_text_color(ui_RRTIRETEMPwhite, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RRTIRETEMPwhite, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RRTIRETEMPwhite, &ui_font_big32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LAPCOUNTERshadow = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LAPCOUNTERshadow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LAPCOUNTERshadow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LAPCOUNTERshadow, -44);
    lv_obj_set_y(ui_LAPCOUNTERshadow, 11);
    lv_obj_set_align(ui_LAPCOUNTERshadow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LAPCOUNTERshadow, "0");
    lv_obj_add_flag(ui_LAPCOUNTERshadow, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LAPCOUNTERshadow, lv_color_hex(0x36380C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LAPCOUNTERshadow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LAPCOUNTERshadow, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LAPCOUNTERshadow, &ui_font_big32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LAPCOUNTERbase = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LAPCOUNTERbase, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LAPCOUNTERbase, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LAPCOUNTERbase, -47);
    lv_obj_set_y(ui_LAPCOUNTERbase, 8);
    lv_obj_set_align(ui_LAPCOUNTERbase, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LAPCOUNTERbase, "0");
    lv_obj_set_style_text_color(ui_LAPCOUNTERbase, lv_color_hex(0xF7FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LAPCOUNTERbase, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LAPCOUNTERbase, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LAPCOUNTERbase, &ui_font_big84, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_Slider1, 1, 100);
    lv_slider_set_value(ui_Slider1, 8, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 219);
    lv_obj_set_height(ui_Slider1, 240);
    lv_obj_set_x(ui_Slider1, -111);
    lv_obj_set_y(ui_Slider1, -3);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider1, &ui_img_fuel_slider_rgb2_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LAPCOUNTERshadow1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LAPCOUNTERshadow1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LAPCOUNTERshadow1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LAPCOUNTERshadow1, 21);
    lv_obj_set_y(ui_LAPCOUNTERshadow1, 28);
    lv_obj_set_align(ui_LAPCOUNTERshadow1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LAPCOUNTERshadow1, "00");
    lv_obj_add_flag(ui_LAPCOUNTERshadow1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LAPCOUNTERshadow1, lv_color_hex(0x36380C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LAPCOUNTERshadow1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LAPCOUNTERshadow1, &ui_font_big32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LAPCOUNTERbase1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LAPCOUNTERbase1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LAPCOUNTERbase1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LAPCOUNTERbase1, 19);
    lv_obj_set_y(ui_LAPCOUNTERbase1, 26);
    lv_obj_set_align(ui_LAPCOUNTERbase1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LAPCOUNTERbase1, "00");
    lv_obj_set_style_text_color(ui_LAPCOUNTERbase1, lv_color_hex(0xF7FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LAPCOUNTERbase1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LAPCOUNTERbase1, &ui_font_big32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AVGfuel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AVGfuel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AVGfuel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AVGfuel, -203);
    lv_obj_set_y(ui_AVGfuel, -58);
    lv_obj_set_align(ui_AVGfuel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AVGfuel, "0");
    lv_obj_set_style_text_color(ui_AVGfuel, lv_color_hex(0xFFE800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AVGfuel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AVGfuel, &ui_font_big48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AzimuthAngle = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AzimuthAngle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AzimuthAngle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AzimuthAngle, -202);
    lv_obj_set_y(ui_AzimuthAngle, 92);
    lv_obj_set_align(ui_AzimuthAngle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AzimuthAngle, "0");
    lv_obj_set_style_text_color(ui_AzimuthAngle, lv_color_hex(0xFFE800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AzimuthAngle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AzimuthAngle, &ui_font_big48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AzimuthLebel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AzimuthLebel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AzimuthLebel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AzimuthLebel, -196);
    lv_obj_set_y(ui_AzimuthLebel, 55);
    lv_obj_set_align(ui_AzimuthLebel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AzimuthLebel, "Live Delta");
    lv_obj_set_style_text_color(ui_AzimuthLebel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AzimuthLebel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AzimuthLebel, &ui_font_big28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_kolo_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 104
    lv_obj_set_x(ui_Image2, 129);
    lv_obj_set_y(ui_Image2, 0);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arrow = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Arrow, &ui_img_arrow_png);
    lv_obj_set_width(ui_Arrow, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_Arrow, LV_SIZE_CONTENT);    /// 73
    lv_obj_set_x(ui_Arrow, 130);
    lv_obj_set_y(ui_Arrow, 57);
    lv_obj_set_align(ui_Arrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Arrow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Arrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_Arrow, 13, -22);
    lv_img_set_angle(ui_Arrow, 1800);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_BACKGROUND = NULL;
    ui_TIreConteainer = NULL;
    ui_LFtire = NULL;
    ui_RFtire = NULL;
    ui_RRtire = NULL;
    ui_LRtire = NULL;
    ui_FLTIRETEMPblack = NULL;
    ui_FLTIRETEMPwhite = NULL;
    ui_FRTIRETEMPblack = NULL;
    ui_FRTIRETEMPwhite = NULL;
    ui_RLTIRETEMPblack = NULL;
    ui_RLTIRETEMPwhite = NULL;
    ui_RRTIRETEMPblack = NULL;
    ui_RRTIRETEMPwhite = NULL;
    ui_LAPCOUNTERshadow = NULL;
    ui_LAPCOUNTERbase = NULL;
    ui_Slider1 = NULL;
    ui_LAPCOUNTERshadow1 = NULL;
    ui_LAPCOUNTERbase1 = NULL;
    ui_AVGfuel = NULL;
    ui_AzimuthAngle = NULL;
    ui_AzimuthLebel = NULL;
    ui_Image2 = NULL;
    ui_Arrow = NULL;

}
